# Generated by Django 3.1.5 on 2021-01-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210127_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
